server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-driver-user?character-Encoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zdf19941118.

    cloud:
        nacos:
          discovery:
            server-addr: 127.0.0.1:8848

  application:
    name: service-driver-user

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
